server:
  bind_addr: ":8080"

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "students"
  sslmode: "disable"

logrus:
  log_level: "debug"

jwt:
  expire: "24h"
  # Нельзя хранить ключи в конфиге
  key: "qwerty123"